### ISSUE TITLE
System python is run instead of the first python found in path 

### ISSUE THREAD

**Issue by SirVer** [rogual/neovim-dot-app#32] opened 2015-04-02 12:52 UTC
Not sure if this is a bug in NeoVim.app. 

With an empty .vimrc:
~~~
$ open NeoVim.app
:py print("hi")
>>> No neovim module found for Python 2.7.6..... 
~~~

It works like this though:
$ open Neovim.app/Contents/MacOS/Neovim
:py print("hi")
hi
~~~~

this seems to pick up that I have a homebrew python installed that has the neovim python installed.

**Comment by kopischke** [comment] 2015-04-02 14:17
I would guess this is because your first invocation launches Neovim.app as a conventional GUI app, i.e. one owned by `launchd`; these do not inherit `$PATH` In OS X.

**Comment by rogual** [comment] 2015-04-07 10:08
Yep, I reckon @kopischke is right. You'll probably have to tell Vim which python to use explicitly in your .nvimrc. Closing this; reopen if I'm wrong.

**Comment by SirVer** [comment] 2015-04-07 19:50
I have no doubts that this is not a bug in Neovim.app, but it is a problem that many users will face: The system python should not be altered, so all Python users will homebrew a version for tinkering. That is also the one they will use to `pip install neovim`. From the top vim plugins, at least two are python based (UltiSnips and YouCompleteMe), so many Vim users will want to use the neovim python client.

My question is: is there an acceptable workaround and can we deploy it to handle this common case?

**Comment by rogual** [comment] 2015-04-07 20:21
I did `pip install neovim` into my system python which is probably why this hasn't caused problems for me. Is there some way of telling Neovim which Python to use? Maybe we could put something in the default nvimrc.

**Comment by rygwdn** [comment] 2015-04-08 00:56
you can specify which python interpreter to use with [`g:python_host_prog`](http://neovim.org/doc/user/nvim_python.html#g:python_host_prog). Maybe Neovim.app could check to see if homebrew python is installed and, if it is, then set `g:python_host_prog`? Or maybe modify the `PATH` by to include `/usr/local/bin` by default?

**Comment by SirVer** [comment] 2015-04-08 06:16
The `g:python_host_prog` variable works great and solves my problem - I missed hat in the documentation.

I think doing magic during Neovim.app startup might backfire - but having a FAQ or a pointer in the readme about `g:python_host_prog` would be great.

**Comment by rogual** [comment] 2015-04-08 11:57
Agreed re. magic. I added a note to README here 64db96e9aa3d1a28f8f5a7de65ceeaa53a540769 which should point people in the right direction.

**Closed by rogual** 2015-04-08 11:57 UTC
Labels: compatibility

**Comment by SirVer** [comment] 2015-04-08 18:59
Perfect. Thanks.

**Comment by khalidchawtany** [comment] 2015-04-11 20:44
I have added the ```let g:python_host_prog='/usr/local/bin/python'``` to the top of my **.nvimrc**. However, when I start **Neovim.app**, I get a message telling me that **Python quit unexpectedly while using the Python plug-in.**. Clicking on the report button shows the report below, which implies that **Neovim.app** is still using system python. However, after I dismiss the error message, I can use python and it's the **HomeBrew** python that is used.

If I remove ```let g:python_host_prog='/usr/local/bin/python'``` from my **.nvimrc**, the error message disappears. However, I cannot use python and **YCM** begins complaining, as the system default python is used.

I am reporting this, since it's very annoying to see an error message every time  you start your editor :)
```
Process:               Python [27469]
Path:                  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.6 (2.7.6)
Code Type:             X86-64 (Native)
Parent Process:        Python [27464]
Responsible:           Neovim [27459]
User ID:               501

PlugIn Path:             /usr/local/Frameworks/Python.framework/Versions/2.7/Python
PlugIn Identifier:       org.python.python
PlugIn Version:          2.7.9, [c] 2004-2014 Python Software Foundation. (2.7.9)

Date/Time:             2015-04-11 23:35:09.988 +0300
OS Version:            Mac OS X 10.10.3 (14D131)
Report Version:        11
Anonymous UUID:        89877AE2-DF0F-88C8-691F-96E2F2DA771D


Time Awake Since Boot: 13000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called



*****************A HUGE BACKTRACE IF NEEDED I WILL SEND IT*******************
```

**Comment by rogual** [comment] 2015-04-11 21:40
Hi, thanks for the bug report. Quick response until I have more time to look into it:

1. Please open a separate issue for this — this issue is closed and was for a different Python-related problem.
2. Can you reproduce with an otherwise-empty .nvimrc?
3. If not, it would be good if you could figure out which of your plugins or settings is causing this to happen
4. Does this happen in plain `nvim` or only in Neovim.app?
