### ISSUE TITLE
line-marks after disappearance the complete popup

### ISSUE THREAD

**Issue by aliev** [rogual/neovim-dot-app#60] opened 2015-04-11 20:46 UTC
Video demonstration: https://dl.dropboxusercontent.com/u/5837324/neovim-dot-app-marks.mov
Screenshot: https://dl.dropboxusercontent.com/u/5837324/scr-neovim-dot-app.jpg

It can be fixed?

**Comment by rogual** [comment] 2015-04-11 21:33
Yeah, looks like the clipping rect just needs adjusting.

**Comment by aliev** [comment] 2015-04-11 21:48
@rogual thanks! :)

**Comment by rogual** [comment] 2015-04-13 13:43
I've adjusted the clipping rect calculations; do you want to check and see if this still happens?

**Comment by aliev** [comment] 2015-04-13 13:51
@rogual I did a git pull (and make clean too). Unfortunately I still see these lines: https://www.dropbox.com/s/3ldl1ankn6ahdqr/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-04-13%2018.48.36.png?dl=0

**Comment by rogual** [comment] 2015-04-15 14:12
This is probably caused by Cocoa's background rectangles (computed from font glyphs using black magic) not being quite equal to our own background rectangles (computed by multiplying `mCellRect` by however many chars we're drawing).

**Comment by bambu** [comment] 2015-09-11 00:17
@aliev I can't see the video or screenshots, but has this been fixed by the recent changes to #109?

**Comment by rogual** [comment] 2015-10-02 12:26
Radio silence, closing. Please reopen if this is still a problem.

**Closed by rogual** 2015-10-02 12:26 UTC
Labels: bug
