### ISSUE TITLE
Unable to type Chinese. What's the reason for that?

### ISSUE THREAD

**Issue by azzsh** [rogual/neovim-dot-app#325] opened 2017-08-12 18:03 UTC
Such as the title, after the installation, you can not input Chinese. Is there a solution?

**Comment by rogual** [comment] 2018-03-01 17:41
> What's the reason for that?

No reason really — just that I haven't needed it and nobody's submitted a PR!

Closing as duplicate of https://github.com/rogual/neovim-dot-app/issues/70 which covers all languages that get input with IMEs.

**Closed by rogual** 2018-03-01 17:41 UTC
