### ISSUE TITLE
Scrolling is slow

### ISSUE THREAD

**Issue by resistor** [rogual/neovim-dot-app#75] opened 2015-04-24 18:07 UTC
I use a Logitech mouse with an "unlockable" scroll wheel for fast scrolling.  While scrolling works fine in the locked mode, when I unlock to scroll quickly Neovim.app becomes very skippy.

**Comment by rogual** [comment] 2015-04-26 07:15
What is the model of your mouse?

**Comment by fritzy** [comment] 2015-04-26 20:00
I have a Logitech mouse with the same feature at my office. I'll try i there and see if I can reproduce for you @rogual. I didn't notice a problem using smooth scrolling with a Mac touchpad though.

**Comment by fritzy** [comment] 2015-04-27 22:52
Scrolling falls behind @rogal -- seeming to send one scroll at a time when it should be skipping a bit with high speed scrolling.

**Comment by shazow** [comment] 2015-05-18 01:04
Same here, using a touchpad, looks like there is a max scroll speed so it effectively ignores the acceleration of my "flick" when I scroll. Macvim.app side-by-side will scroll all the way to the bottom with a single swift flick nearly instantly, whereas Neovim.app reaches a maximum scroll speed and keeps scrolling at that rate for a while before stopping. I can record a video if that helps.

**Comment by rogual** [comment] 2015-09-01 14:37
I'm going to close this in favour of https://github.com/rogual/neovim-dot-app/issues/99 since it's not specifically scrolling that's slow. Fixing the text renderer should also fix scrolling performance.

**Closed by rogual** 2015-09-01 14:37 UTC
