### ISSUE TITLE
Should --libs msgpack be msgpackc?

### ISSUE THREAD

**Issue by chancez** [rogual/neovim-dot-app#243] opened 2016-04-13 00:23 UTC
Referring to this: https://github.com/rogual/neovim-dot-app/blob/master/SConstruct#L12

I ask because I'm getting the following when trying to install via brew:

```
~/g/s/g/c/soy ❯❯❯ brew install neovim-dot-app                                                                                                                                                                      ⏎ email_invited_no_jobs ✭
==> Installing neovim-dot-app from rogual/neovim-dot-app
==> Downloading https://github.com/rogual/neovim-dot-app/archive/0.1.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/neovim-dot-app-0.1.2.tar.gz
==> make NVIM=/usr/local/opt/neovim/bin/nvim
Last 15 lines from /Users/chance/Library/Logs/Homebrew/neovim-dot-app/01.make:
clang++ -o build/font.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/font.mm
clang++ -o build/graphics.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/graphics.mm
clang++ -o build/input.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/input.mm
clang++ -o build/keys.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/keys.mm
clang++ -o build/main.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/main.mm
clang++ -o build/menu.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/menu.mm
gperf -cCD -L C++ -Z RedrawHash -t src/redraw.gperf > build/redraw-hash.gen.h
clang++ -o build/redraw.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/redraw.mm
clang++ -o build/view.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/view.mm
clang++ -o build/window.o -c -std=c++11 -stdlib=libc++ -g -Wno-deprecated-register -I/usr/local/Cellar/msgpack/1.4.1/include -Ibuild -Isrc src/window.mm
clang++ -o build/Neovim.app/Contents/MacOS/Neovim build/client.o build/process.o build/rpc.o build/vim.o build/vimutils.o build/app.o build/font.o build/graphics.o build/input.o build/keys.o build/main.o build/menu.o build/redraw.o build/view.o build/window.o -L/usr/local/Cellar/msgpack/1.4.1/lib -lmsgpackc -lc++ -lmsgpack -framework Cocoa -framework Carbon
ld: library not found for -lmsgpack
clang: error: linker command failed with exit code 1 (use -v to see invocation)
scons: *** [build/Neovim.app/Contents/MacOS/Neovim] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/rogual/homebrew-neovim-dot-app/issues

```

**Comment by dylanscott** [comment] 2016-04-13 15:21
I'm getting this same issue. I've seen some reports of people seeing this when they didn't have the XCode command line tools installed, but I definitely have them installed. I can `brew uninstall msgpack` and see that `brew install neovim-dot-app` reinstalls it as a dependency but still fails to link.

**Comment by dylanscott** [comment] 2016-04-13 15:37
Actually it looks like this may be a dupe of #184, which was fixed with 7ca70378c32a57575310c405bb5100290c716692.

Unfortunately I wasn't able to see if that fixes the issue because `brew install --HEAD neovim-dot-app` tells me that it needs a newer neovim version (1.3.0-202 vs 1.3.0-0) and trying to `brew upgrade --HEAD neovim` fails for me with something about `luv-static` (presumably libuv related). Couldn't get neovim to upgrade even by uninstalling, blowing away homebrew cache, and reinstalling.

**Comment by chancez** [comment] 2016-04-13 16:50
@dylanscott You need to have the full xcode suite, not just command line tools regarding the first part.

**Comment by dylanscott** [comment] 2016-04-13 16:54
I believe I do - at least I can launch the XCode application, and running `xcode-select --install` yields

```
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by gwerbin** [comment] 2016-04-15 15:56
@dylanscott I managed to get it to work using the `--HEAD` versions of both NeoVim and NeoVim-dot-app.

**Comment by dylanscott** [comment] 2016-04-15 16:22
@gwerbin that worked for me now, not seeing the `luv-static` error anymore 👍

**Comment by rogual** [comment] 2016-06-11 18:22
Created a new release 0.1.4 and added it to the Homebrew formula. `brew install` should now work without `--HEAD`.

**Closed by rogual** 2016-06-11 18:22 UTC

**Comment by abaldwin88** [comment] 2016-06-15 13:01
@rogual  Not sure if I'm doing something wrong but `brew install neovim-dot-app` was using version 0.1.2.  I had to use `brew install --HEAD neovim-dot-app` to get the build to complete.
