### ISSUE TITLE
YouCompleteMe with Homebrew Python causes errors

### ISSUE THREAD

**Issue by khalidchawtany** [rogual/neovim-dot-app#61] opened 2015-04-11 21:58 UTC
I have added the ```let g:python_host_prog='/usr/local/bin/python'``` to the top of my **.nvimrc**. However, when I start **Neovim.app**, I get a message telling me that **Python quit unexpectedly while using the Python plug-in.**. Clicking on the report button shows the report below, which implies that **Neovim.app** is still using system python. However, after I dismiss the error message, I can use python and it's the **HomeBrew** python that is used.

If I remove ```let g:python_host_prog='/usr/local/bin/python'``` from my **.nvimrc**, the error message disappears. However, I cannot use python and **YCM** begins complaining, as the system default python is used.

This issued happens only in **neovim-dot-app** when **YCM** is used. Without, **YCM** everything goes smoothly. If I use **nvim** inside terminal, with the same **.nvimrc** no error is displayed.

```
Process:               Python [27469]
Path:                  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.6 (2.7.6)
Code Type:             X86-64 (Native)
Parent Process:        Python [27464]
Responsible:           Neovim [27459]
User ID:               501

PlugIn Path:             /usr/local/Frameworks/Python.framework/Versions/2.7/Python
PlugIn Identifier:       org.python.python
PlugIn Version:          2.7.9, [c] 2004-2014 Python Software Foundation. (2.7.9)

Date/Time:             2015-04-11 23:35:09.988 +0300
OS Version:            Mac OS X 10.10.3 (14D131)
Report Version:        11
Anonymous UUID:        89877AE2-DF0F-88C8-691F-96E2F2DA771D


Time Awake Since Boot: 13000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called



*****************A HUGE BACKTRACE IF NEEDED I WILL SEND IT*******************
```

**Comment by alaroldai** [comment] 2015-04-12 01:38
It looks like the `environ` global variable is incorrect: on my machine the PATH from `environ` is `/usr/bin:/bin:/usr/sbin:/sbin`, but running `launchctl getenv path` from any terminal returns the correct path, with `/usr/local/bin` listed first. Possibly there's an Info.plist flag or something that needs to be set for Launch Services to set the environment variables correctly?

**Comment by rogual** [comment] 2015-04-12 09:31
@khalidchawtany thanks for opening a new issue for this. Copying my questions from the old one:
1. Can you reproduce with an otherwise-empty .nvimrc?
2. If not, it would be good if you could figure out which of your plugins or settings is causing this to happen
3. Does this happen in plain nvim or only in Neovim.app?

@alaroldai I don't know where `/usr/local/bin` gets added to your path on your machine, but on mine it's in `~/.bash_profile` so it makes sense that this would only be present when things are launched through Bash.

**Comment by alaroldai** [comment] 2015-04-12 10:29
I'm adding it through `launchctl setenv`, so it should be present throughout the whole login session.

**Comment by khalidchawtany** [comment] 2015-04-12 15:40
@rogual I have already stated that:
 This issued happens only in neovim-dot-app when YCM is used. Without, YCM everything goes smoothly. If I use nvim inside terminal, with the same .nvimrc no error is displayed. If the .nvimrc is empty I don't get any errors.

**Comment by rogual** [comment] 2015-04-13 13:44
Oh yes, must have missed that. My bad.

**Comment by rogual** [comment] 2015-04-13 14:25
@alaroldai According to my experiments, `launchctl setenv` will happily set any environment variable except `PATH`. If I just echo out `getenv("PATH")` as the first line in `main`, I still get launchd's default path, even if I've used `launchctl setenv PATH blah`. This doesn't seem to apply to other env vars.

This post suggests `launchd.conf`: http://stackoverflow.com/questions/135688/setting-environment-variables-in-os-x — you might have more luck with that.

Or perhaps set your path from within Vim — not sure if Vimscript has a setenv-alike function.

**Comment by rogual** [comment] 2015-04-13 14:32
@khalidchawtany OK, I've installed YCM, and I now get a similar issue to yours. It doesn't happen as soon as Neovim.app starts, but pretty consistently after a little bit of editing. I get:

    The ycmd server SHUT DOWN (restart with :YcmRestartServer). Stderr (last 30 lines):
    Press ENTER or type command to continue

I guess this would be consistent with your report of Python itself crashing.

On doing `:YcmRestartServer` it happens again pretty quickly.

**Comment by khalidchawtany** [comment] 2015-04-13 14:44
I get that same error too. However, I was not sure whether YCM works or not. Since, I am currently not working on anything that would need YCM :)

I just did ```sudo pip install neovim``` and the error is still there :(

**Comment by khalidchawtany** [comment] 2015-04-13 14:52
@rogual you are right, ```:YcmRestartServer``` produces the same error.

**Comment by alaroldai** [comment] 2015-04-14 06:51
So I've taken a look at MacVim's source code, and it looks like MacVim launches it's vim subprocess from a login shell (see `MMAppController.m`, line 1503). The documentation for the related method (`- executeInLoginShell:arguments`) states:
```
    // Start a login shell and execute the command 'path' with arguments 'args'
    // in the shell.  This ensures that user environment variables are set even
    // when MacVim was started from the Finder.
```
So it looks like we'll need to do a similar thing here, either by actually running a command through `bash` or by reading the output from `launchctl getenv` and setting up Neovim's environment manually.

**Comment by alaroldai** [comment] 2015-04-15 00:30
I've created a pull request (#67) that should resolve these issues. On my machine it fixes the issues with YouCompleteMe, and also with other plugins using external programs, such as Clighter.

**Comment by khalidchawtany** [comment] 2015-04-15 07:59
Thanks for the hard work.

**Comment by khalidchawtany** [comment] 2015-04-15 08:41
Thanks @alaroldai, #67 solves my problem.

**Comment by rogual** [comment] 2015-04-15 11:47
Merged https://github.com/rogual/neovim-dot-app/pull/67 and it fixes this for me too.

**Closed by rogual** 2015-04-15 11:47 UTC
