### ISSUE TITLE
Can't open files via open -a Neovim

### ISSUE THREAD

**Issue by ilsken** [rogual/neovim-dot-app#146] opened 2015-09-26 06:02 UTC
Every file type gives me this:
<img width="443" alt="screen shot 2015-09-26 at 1 44 18 am" src="https://cloud.githubusercontent.com/assets/554927/10116079/7ff6cdec-63f2-11e5-847c-5b06fbe1974f.png">

When using `open -a Neovim <file>`

**Comment by bambu** [comment] 2015-09-26 13:08
This issue is already known and being worked. :) Take a look at PR #127

**Comment by ilsken** [comment] 2015-09-28 16:32
Whoops! Sorry about all the noise. Looking forward to seeing this issue resolved! Great work by the way, I am very excited about this project.

**Comment by rogual** [comment] 2015-10-29 13:45
OK! I have merged PR #127 and it seems that this does fix the issue BUT `open` appears to keep a VERY aggressive cache regarding which apps can open what.

After making the change, if I rename Neovim.app to Neovim1.app I can do `open -a Neovim1 somefile` just fine, but renaming it back causes the old "cannot open files" error. Even restarting my computer didn't help.

This only seems to affect the `open` command — I can open files in Neovim through Finder without a problem.

So, if anyone knows how to manually clear this cache, do say! Otherwise, I'm pretty sure the issue is fixed.

**Comment by rogual** [comment] 2015-10-30 13:41
For anyone else having that issue, I discovered that `open` was looking not only in /Applications but also somewhere deep in ~/Library/Developer (!)

Fixed that and this issue appears to be resolved.

**Closed by rogual** 2015-10-30 13:41 UTC
