### ISSUE TITLE
gnvim starts new instance every time

### ISSUE THREAD

**Issue by robguthrie** [rogual/neovim-dot-app#271] opened 2016-06-26 06:52 UTC
Hope this is an ok place to ask.

I'm expecting that when I run `gnvim filename` it'll open `filename` in a new window of the existing instance of neovim dot app.. but it starts another instance with another icon on the taskbar.

How can I get the behaviour that I'm expecting? (similar behaviour to macvim, atom)

Thanks for this great program and for your support.

**Comment by rogual** [comment] 2016-06-26 10:07
Duplicate of https://github.com/rogual/neovim-dot-app/issues/226

**Closed by rogual** 2016-06-26 10:07 UTC
