### ISSUE TITLE
Ctrl-space is not captured 

### ISSUE THREAD

**Issue by TyOverby** [rogual/neovim-dot-app#257] opened 2016-05-11 00:35 UTC
I use the [ctrlspace](https://github.com/vim-ctrlspace/vim-ctrlspace) plugin, but the default keybinding (ctrl-space) does not work in neovim-dot-app.

**Comment by bambu** [comment] 2016-05-11 01:25
The problem seems to be that Neovim.app is actually sending `<c-space>` to nvim but the vim-ctrlspace plugin defaults to terminal mapping of `<nul>`. commenting out the following lines is a quick way to resolve the problem.

[vim-ctrlspace/autoload/ctrlspace/keys.vim#L155-157](https://github.com/vim-ctrlspace/vim-ctrlspace/blob/f7987e4e21b238732632be704d033a73aacbb65d/autoload/ctrlspace/keys.vim#L155-157)
_(Not sure if there's a way in github to actually show the code from that file in this post)_

Another way to 'resolve' the issue is to have the following mapping: 
```viml
if exists('g:neovim_dot_app')
  nmap <c-space> <nul> 
end
```

**Comment by rogual** [comment] 2016-06-11 17:59
The only thing we could really do in Neovim.app to fix this is to send `<nul>` instead of `<c-space>`. But, we aren't a terminal, and I prefer the consistency of sending `<c-space>`.

Given that vim-ctrlspace is already doing platform detection here (`!has("gui_running") && !has("win32")`) I think the right fix for this is to add Neovim.app detection to vim-ctrlspace (`!exists("g:neovim_dot_app")`).

Please use @bambu's workaround in the meantime.

**Closed by rogual** 2016-06-11 17:59 UTC
